name: Ansible Deployment

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an appropriate runner based on your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for authentication
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 165.232.131.61 >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.yml playbook.yml
      env:
        ANSIBLE_FORCE_COLOR: '1'  # This ensures colored output in GitHub Actions

env:
  ANSIBLE_HOST_KEY_CHECKING: false
