name: LAMP Deployement 

on:
    workflow_dispatch:
jobs:
  linting:
    name: Lint Ansible files 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v6.20.3
        with:
          targets: |
            ./playbook.yml
            ./inventory.yml
            